### ISSUE TITLE
希望新增解打包“.bin”格式的ROM文件

### ISSUE THREAD

**Issue by TG-Twilight** [ColdWindScholar/TIK#12]
希望新增解打包“.bin”格式的ROM文件，“.bin”格式常用于各类电视机的系统刷写，这些刷机包通常内置了许多流氓软件，需要精简。

[示例文件](https://ufile.io/u3zz5agv)

**Comment by ColdWindScholar** [comment]
good idea.

**Comment by TG-Twilight** [comment]
对了，这里提供一个针对 “.bin” 的ROM文件可用的解包工具

[#长虹整机厂USB升级包-海思格式bin解包工具.zip](https://github.com/ColdWindScholar/TIK/files/15211436/USB.-.bin.zip)

**Comment by yeliqin666** [comment]
此类二进制文件类型众多，后续将以插件形式提供更多支持
