### ISSUE TITLE
解压uboot失败

### ISSUE THREAD

**Issue by YedLeo1** [ColdWindScholar/TIK#17]
ERROR:FileNotFoundError
[Errno 2] No such file or directory: 'D:\\Users\\88058\\Desktop\\1\\TIK-5-122-win_2\\1\\\\config\\dtbinfo_uboot' 

[uboot.zip](https://github.com/user-attachments/files/15747486/uboot.zip)

**Comment by yeliqin666** [comment]
已修复，感谢反馈

**Comment by YedLeo1** [comment]
你知道这个是什么分区吗，一点信息都搜不到
[security.zip](https://github.com/user-attachments/files/15856017/security.zip)
