### ISSUE TITLE
super打包错误

### ISSUE THREAD

**Issue by YedLeo1** [ColdWindScholar/TIK#18]
这又是啥问题，之前tik4可以打包的

![image](https://github.com/ColdWindScholar/TIK/assets/121866890/c3545e12-420a-40a6-ab34-bb492628b39c)

**Comment by ColdWindScholar** [comment]
Fixed!

**Comment by YedLeo1** [comment]
![image](https://github.com/ColdWindScholar/TIK/assets/121866890/5587cbae-c9cf-4872-b078-c36a829dcc21)

**Comment by YedLeo1** [comment]
一模一样的文件

**Comment by ColdWindScholar** [comment]
我已经修完了

**Comment by YedLeo1** [comment]
谢谢
