### ISSUE TITLE
error mac

### ISSUE THREAD

**Issue by davikl** [ColdWindScholar/TIK#19]
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                   ERROR:Exception                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│              Describe:Binary not found               │
│             May Not Support Your Device?             │
│           Lines:136       Module:__main__            │
├──────────────────────────────────────────────────────┤
│         Platform:arm64  System:Darwin 23.2.0         │
│         Python:3.11.2   Tool Version:Unknown         │
├──────────────────────────────────────────────────────┤
│ Report:https://github.com/ColdWindScholar/TIK/issues │
└──────────────────────────────────────────────────────┘

**Comment by ColdWindScholar** [comment]
ok， will fix

**Comment by 2392338840** [comment]
对vendor.img解包再重新打包，打包出来的文件比原文件大了两百多兆，刷不进去，怎么办？
