### ISSUE TITLE
an error occurred while unpacking hyperOS 

### ISSUE THREAD

**Issue by Sddsfdd** [ColdWindScholar/TIK#24]
![image](https://github.com/user-attachments/assets/7f76e01f-6311-4134-866c-91ada0c1c300)
image version: images_OS1.0.3.0.UMRCNXM_14.0

**Comment by ColdWindScholar** [comment]
？logs?

**Comment by Sddsfdd** [comment]
> ？logs?
Forgive me, I really don't know where the log file is

**Comment by Sddsfdd** [comment]
; ^ ;

**Comment by ColdWindScholar** [comment]
try it https://github.com/ColdWindScholar/TIK/releases/tag/GLOBAL_CI_BUILD_137

**Comment by Sddsfdd** [comment]
> try it https://github.com/ColdWindScholar/TIK/releases/tag/GLOBAL_CI_BUILD_1
appreciate♪(^∇^*)
