### ISSUE TITLE
TIK-5.318-WIN中未加入payload-dumper-go

### ISSUE THREAD

**Issue by Lightdust2024** [ColdWindScholar/TIK#25]
手动加入payload-dumper-go之前：
![image](https://github.com/user-attachments/assets/eb921c84-0c40-4f11-823b-f6070abef0ea)
手动加入payload-dumper-go之后：
![image](https://github.com/user-attachments/assets/c319bc47-dbae-44c3-897c-3688eb4049c2)
如图，代码中已经集成该功能，所以希望加入payload-dumper-go.exe，一步到位

**Comment by ColdWindScholar** [comment]
可能是我忘记删除payload-dumper的调用了
