### ISSUE TITLE
解包mi_ext_a.img长时间不动

### ISSUE THREAD

**Issue by Cathgao** [ColdWindScholar/TIK#26]
任务管理器中磁盘没有任何占用，CPU在10%以下
![截图20240725092750](https://github.com/user-attachments/assets/4dc12d8b-6357-4222-aed8-56c184fbc1b1)

[mi_ext_a.zip](https://github.com/user-attachments/files/16369047/mi_ext_a.zip)

**Comment by ColdWindScholar** [comment]
thanks, i will fix it

**Comment by ColdWindScholar** [comment]
Fixed, testing

**Comment by ColdWindScholar** [comment]
Thanks For Your Issues! Fixed, please download from https://github.com/ColdWindScholar/TIK/releases/tag/CI_BUILD_142

**Comment by Cathgao** [comment]
这个CI build解包product失败，而141可以正常解包
![image](https://github.com/user-attachments/assets/e5882fc6-d0d2-42a9-b344-cc61c5eb8020)
![image](https://github.com/user-attachments/assets/47ad3286-a610-4f34-ab3c-9eec998b2e50)

**Comment by ColdWindScholar** [comment]
what?

**Comment by ColdWindScholar** [comment]
ok, i wilkl fix

**Comment by ColdWindScholar** [comment]
https://github.com/ColdWindScholar/TIK/releases/tag/CI_BUILD_143
