### ISSUE TITLE
实测,无法解包损坏的.dat文件

### ISSUE THREAD

**Issue by ozbao** [ColdWindScholar/TIK#27]
![Uploading image.png…]()
任意按钮继续,无线循环

**Comment by ozbao** [comment]
![1722057940997](https://github.com/user-attachments/assets/31254b3b-567c-4ecf-bd80-ba679720e362)

**Comment by ColdWindScholar** [comment]
哥们，发我，你不发是想让我红温吗？

**Comment by ColdWindScholar** [comment]
哥们，这玩意不是工具问题，是镜像问题。

**Comment by ozbao** [comment]
链接：https://pan.baidu.com/s/1z_QzRFpuKQvTUJ9KonpvBA?pwd=4fsa 
提取码：4fsa

**Comment by ozbao** [comment]
> 哥们，这玩意不是工具问题，是镜像问题。

链接：https://pan.baidu.com/s/1z_QzRFpuKQvTUJ9KonpvBA?pwd=4fsa 
提取码：4fsa

**Comment by ozbao** [comment]
> > 哥们，这玩意不是工具问题，是镜像问题。
> 
> 链接：https://pan.baidu.com/s/1z_QzRFpuKQvTUJ9KonpvBA?pwd=4fsa 提取码：4fsa

这是tiktok的apk,tt_icudtl.dat文件

**Comment by ColdWindScholar** [comment]
> > > 哥们，这玩意不是工具问题，是镜像问题。
> > 
> > 
> > 链接：https://pan.baidu.com/s/1z_QzRFpuKQvTUJ9KonpvBA?pwd=4fsa 提取码：4fsa
> 
> 这是tiktok的apk,tt_icudtl.dat文件

你无敌了， 我们不会受理该issue

**Comment by ozbao** [comment]
> > > > 哥们，这玩意不是工具问题，是镜像问题。
> > > 
> > > 
> > > 链接：https://pan.baidu.com/s/1z_QzRFpuKQvTUJ9KonpvBA?pwd=4fsa 提取码：4fsa
> > 
> > 
> > 这是tiktok的apk,tt_icudtl.dat文件
> 
> 你无敌了， 我们不会受理该issue

.dat应该是没有损坏,可能加了点其他处理,你的工具很好,就是建议如果不支持这类型.dat的话,输出个提示就更好了

**Comment by Cathgao** [comment]
这是处理系统镜像的工具，你搞个apk里面的dat干嘛，你是觉得后缀一样就是一样的文件吗
