### ISSUE TITLE
最新版本5.158貌似出现乱码

### ISSUE THREAD

**Issue by RainGreenleaf** [ColdWindScholar/TIK#33]
5.158版本貌似出现乱码
5.157版本变为英文
5.156版本为正常

![image](https://github.com/user-attachments/assets/ae458196-af8f-4504-a12c-8b8d8cc28750)

**Comment by 0chan-0bit** [comment]
最新构建是RU CI，所以是俄语

**Comment by RainGreenleaf** [comment]
> 最新构建是RU CI，所以是俄语

或许需要做个语言切换?
