### ISSUE TITLE
打开后显示的是如下乱码

### ISSUE THREAD

**Issue by reddy-quan** [ColdWindScholar/TIK#43]
打开后显示的是如下乱码：

[31m
 _________  ___  ___  __    ________
|\___   ___|\  \|\  \|\  \ |\   ____\
\|___ \  \_\ \  \ \  \/  /|\ \  \___|_
     \ \  \ \ \  \ \   ___  \ \_____  \
      \ \  \ \ \  \ \  \\ \  \|____|\  \
       \ \__\ \ \__\ \__\\ \__\____\_\  \
        \|__|  \|__|\|__| \|__|\_________\
                              \|_________|
 [0m
[93;44m Альфа версия [0m
[36m “支离东北风尘际，漂泊西南天地间。”
[36m---杜甫《咏怀古迹五首·其一》[0m

 >[33m Список проектов [0m

[31m   [00]  Удалить проект[0m

   [0]  Создать новый проект

  --------------------------------------
[33m  [55] Распаковать  [66] Выйти из программы  [77
] Настройки  [88] Скачать прошивку[0m

  Пожалуйста, введите число：

**Comment by reddy-quan** [comment]
我的系统是老win7，我改为直接运行源码，python run.py后至少菜单能显示了，但前面的颜色参数[31m还是以乱码出现。

[31m
 _________  ___  ___  __    ________
|\___   ___|\  \|\  \|\  \ |\   ____\
\|___ \  \_\ \  \ \  \/  /|\ \  \___|_
     \ \  \ \ \  \ \   ___  \ \_____  \
      \ \  \ \ \  \ \  \\ \  \|____|\  \
       \ \__\ \ \__\ \__\\ \__\____\_\  \
        \|__|  \|__|\|__| \|__|\_________\
                              \|_________|
 [0m
[93;44m Alpha Edition [0m
[36m “霜风渐欲作重阳，熠熠溪边野菊香。”
[36m---苏轼《捕蝗至浮云岭山行疲苶有怀子由弟二首·其二》[0m

 >[33m 项目列表 [0m

[31m   [00]  删除项目[0m

   [0]  新建项目

   [1]  mytv

   [2]  update

   [3]  __pycache__

  --------------------------------------
[33m  [55] 解压  [66] 退出  [77] 设置  [88] 下载ROM[0m

  请输入序号：

**Comment by univers629** [comment]
[GLOBAL_CI_BUILD_157](https://github.com/ColdWindScholar/TIK/releases/tag/GLOBAL_CI_BUILD_157)
[CI_BUILD_156](https://github.com/ColdWindScholar/TIK/releases/tag/CI_BUILD_156)

**Comment by univers629** [comment]
> 打开后显示的是如下乱码：
> 
> �[31m
> 
> |___ _**|\ |\ |\ \ |\ __** |**_ \ _\ \ \ \ / /|\ \ _**|_ \ \ \ \ \ \ \ ___ \ _____ \ \ \ \ \ \ \ \ \ |____|\ \ __\ \ __\ __\ ____**_\ |**| |__||__| |__|___** |**___| �[0m �[93;44m Альфа версия �[0m �[36m “支离东北风尘际，漂泊西南天地间。” �[36m---杜甫《咏怀古迹五首·其一》�[0m
> 
> > �[33m Список проектов �[0m
> 
> �[31m [00] Удалить проект�[0m
> 
> [0] Создать новый проект
> 
> �[33m [55] Распаковать [66] Выйти из программы [77 ] Настройки [88] Скачать прошивку�[0m
> 
> Пожалуйста, введите число：

你这不是俄语吗，哪里是乱码？
