### ISSUE TITLE
请求支持 F2FS 格式

### ISSUE THREAD

**Issue by AiKirito** [ColdWindScholar/TIK#5]
在遇到该格式的 img 时，貌似无法识别并提取

**Comment by ColdWindScholar** [comment]
收到！

**Comment by ColdWindScholar** [comment]
give me a f2fs images

**Comment by ColdWindScholar** [comment]
wtf
 不应该啊

**Comment by ColdWindScholar** [comment]
![880d1ad38d0319d7c88706d04660af56](https://github.com/ColdWindScholar/TIK/assets/140364844/1f5e3b87-def6-4e4b-ac72-1db751eedc9a)

**Comment by ColdWindScholar** [comment]
Simg2img works fine

**Comment by ColdWindScholar** [comment]
您的镜像可能是加密的

**Comment by ColdWindScholar** [comment]
测试了 确实存在此问题 原因未知

**Comment by ColdWindScholar** [comment]
离谱

**Comment by yeliqin666** [comment]
TIK5已加入f2fs支持，问题已解决
