### ISSUE TITLE
run.py 144 行语法无效

### ISSUE THREAD

**Issue by zhaoxitao** [ColdWindScholar/TIK#7]
按照提示编译的时候提示语法无法，是我python版本不对？

$ ython3 --version
Python 3.6.9

$ uname -a
Linux MACHC-WAX9 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Issue:
$  python3 run.py 

 _Output:_
  File "run.py", line 144
    "1": lambda: settings.change('brcom', brcom if (brcom := input(
                                                          ^
SyntaxError: invalid syntax

**Comment by ColdWindScholar** [comment]
你好，支持的Python最低版本是3.8
